version: "3.7"

services:
  gateway:
    profiles: ["openmrs3", "fhir"]
    container_name: openmrs-gateway
    image: openmrs/openmrs-reference-application-3-gateway:${TAG:-nightly}
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

  frontend:
    profiles: ["openmrs3", "fhir"]
    container_name: openmrs-frontend
    image: msfocg/openmrs3-frontend:dev
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS: /openmrs/spa/custom-config.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
    depends_on:
      - backend

  backend:
    profiles: ["openmrs3", "openmrs", "fhir"]
    container_name: openmrs-backend
    image: msfocg/openmrs3-backend:dev
    depends_on:
      - db
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: ${OPENMRS_DB_USER:-openmrs}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OPENMRS_DB_PASSWORD:-openmrs}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data
      - ./distro/configuration:/openmrs/distribution/openmrs_config
      - ./distro/openmrs_modules/event-2.10.0.omod:/openmrs/distribution/openmrs_modules/event-2.10.0.omod
      - ./distro/openmrs_modules/labonfhir-1.3.1-SNAPSHOT.omod:/openmrs/distribution/openmrs_modules/labonfhir-1.3.1-SNAPSHOT.omod

  # MariaDB
  db:
    profiles: ["openmrs3", "openmrs", "fhir"]
    container_name: openmrs-db
    image: mariadb:10.8.2
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    healthcheck:
      test: "mysql --user=${OMRS_DB_USER:-openmrs} --password=${OMRS_DB_PASSWORD:-openmrs} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OMRS_DB_USER:-openmrs}
      MYSQL_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-openmrs}
    ports: 
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./FHIR/mysql.cnf:/etc/mysql/conf.d/custom.cnf  # mysql config preconfigured to allow binlog/debezium

  # FHIR store
  fhir:
    profiles: ["openmrs3", "openmrs", "fhir"]
    container_name: external-fhir-api
    image: hapiproject/hapi:latest
    ports:
     - "8081:8080"
    restart: always
    environment:
      - hapi.fhir.auto_create_placeholder_reference_targets=true
      - hapi.fhir.allow_placeholder_references=true
      - hapi.fhir.allow_external_references=true

  streaming-binlog: 
    profiles: ["openmrs3", "openmrs", "fhir"]
    image: openmrsinfra/openmrs-fhir-analytics:plir-binlog
    container_name: plir-streaming-pipeline
    network_mode: host
    healthcheck:
      test: "exit 0"
    volumes:
      - ./FHIR/dbz_event_to_fhir_config.json:/deployments/dbz_event_to_fhir_config.json
    environment:
      - OPENMRS_URL=http://localhost/openmrs
      - OPENMRS_USERNAME=admin
      - OPENMRS_PASSWORD=Admin123
      - SINK_URL=http://localhost:8081/fhir
      - SINK_USERNAME=hapi
      - SINK_PASSWORD=Admin123
      - JDBC_FETCH_SIZE=10000
      - JDBC_MAX_POOL_SIZE=50
      - JDBC_INITIAL_POOL_SIZE=10
      - JDBC_URL=jdbc:mysql://localhost:3307/openmrs
      - JDBC_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - FHIR_DEBEZIUM_CONFIG_PATH=/deployments/dbz_event_to_fhir_config.json   

volumes:
  openmrs-data: ~
  db-data: ~