---
- name: Setup Docker, Docker-compose, Git and Deploy OpenMRS 3
  hosts: all
  become: yes
  vars:
    app_repository: https://github.com/MSF-OCG/LIME-EMR-project-demo.git
    app_url: http://localhost
    app_admin_url: http://localhost/openmrs/admin
  tasks:
    - name: Install prerequisites for MacOS
      when: ansible_os_family == "Darwin"
      block:
        - name: Install Docker-compose
          command: brew install docker-compose
          become: no
        - name: Install Git
          command: brew install git
          become: no

    - name: Install prerequisites for Ubuntu
      when: ansible_os_family == "Debian"
      block:
        - name: Install Docker
          apt:
            name: docker.io
            state: present
        - name: Install Docker-compose
          apt:
            name: docker-compose
            state: present
        - name: Install Git
          apt:
            name: git
            state: present

    - name: Check if dest_folder is empty
      find:
        paths: "{{ dest_folder }}"
        file_type: any
      register: folder_contents

    - name: Clone repository if dest_folder is empty
      git:
        repo: "{{ app_repository }}"
        dest: "{{ dest_folder }}"
        clone: yes
        update: no
      when: folder_contents.matched == 0
    
    - name: Grant write access to a file/directory
      file:
        path: "{{ dest_folder }}"
        mode: '0775'  
        recurse: yes 

    - name: Pull latest commits if dest_folder is not empty
      git:
        repo: "{{ app_repository }}"
        dest: "{{ dest_folder }}"
        clone: no
        update: yes
        force: yes
      when: folder_contents.matched > 0

    - name: Pull images using Docker Compose
      community.docker.docker_compose:
        project_src: "{{ dest_folder }}"
        pull: yes
      register: docker_compose_pull_result
    
    - name: Run docker-compose with OpenMRS3 profile
      community.docker.docker_compose:
        project_src: "{{ dest_folder }}"
        profiles:
          - openmrs3
        state: present
        detached: yes
      register: docker_compose_up_result

    - name: Display Docker Compose up result
      debug:
        var: docker_compose_up_result

    - name: Wait for a few seconds for containers to start
      wait_for:
        timeout: 10

    - name: Confirm Docker containers are running
      command: docker ps
      register: docker_ps_output
      changed_when: false

    - name: Wait for a few seconds for containers to start
      wait_for:
        timeout: 60

    - name: Verify if OpenMRS admin is accessible
      uri:
        url: "{{ app_admin_url }}"
        method: GET
        status_code: 200
      register: result

    - name: Display URL check result
      debug:
        msg: "OpenMRS Administration is accessible!"
      when: result.status == 200

    - name: Display URL check failure
      debug:
        msg: "OpenMRS Administration is NOT accessible!"
      when: result.status != 200
