---
- name: Setup Docker, Docker-compose, Git and Deploy OpenMRS 3
  hosts: all
  become: yes
  vars:
    app_repository: https://github.com/MSF-OCG/LIME-EMR-project-demo.git
    app_url: http://localhost
  tasks:
    - name: Install prerequisites for MacOS
      when: ansible_os_family == "Darwin"
      block:
        - name: Install Docker-compose
          command: brew install docker-compose
          become: no
        - name: Install Git
          command: brew install git
          become: no

    - name: Install prerequisites for Ubuntu
      when: ansible_os_family == "Debian"
      block:
        - name: Install Docker
          apt:
            name: docker.io
            state: present
        - name: Install Docker-compose
          apt:
            name: docker-compose
            state: present
        - name: Install Git
          apt:
            name: git
            state: present

    - name: Clone the Git repository
      git:
        repo: "{{ app_repository }}"
        dest: "{{ dest_folder }}"
        version: "{{ git_branch }}"
        force: yes

    - name: Run Docker-compose
      command: docker-compose up -d
      args:
        chdir: "{{ dest_folder }}"

    - name: Wait for a few seconds for containers to start
      wait_for:
        timeout: 10

    - name: Confirm Docker containers are running
      command: docker ps
      register: docker_ps_output
      changed_when: false

    - name: Verify localhost is available
      uri:
        url: "{{ app_url: }}"
        status_code: 200
      register: localhost_response

    - name: Fail if localhost is not available
      fail:
        msg: "Localhost is not available!"
      when: localhost_response.status != 200
