name: Package Ansible Folder

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'Ansible/**'
  pull_request:
    paths:
      - 'Ansible/**'

jobs:
  upload-artifact:
      name: '📦 Release'
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Zip the folder
        run: zip -r ansible_artifact.zip ./Ansible/*
  
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'nightly'
          rm: true
          files: |
            ansible_artifact.zip
