name: Package Ansible Folder

on:
  workflow_dispatch:
  push:
    paths:
      - 'Ansible/**'
  pull_request:
    paths:
      - 'Ansible/**'

jobs:
  upload-artifact:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Tar files
        run: tar -cvf ansible_artifact.tar ./Ansible
        
      - uses: actions/download-artifact@v2
        with:
          path: ./Ansible

      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets._GITHUB_TOKEN }}
          tag: 'nightly'
          files: |
            ansible_artifact.tar
