name: Package Ansible Folder

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'Ansible/**'
  pull_request:
    paths:
      - 'Ansible/**'

jobs:
  upload-artifact:
      name: '📦 Release'
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Tar files
        run: tar -czvf ansible_artifact.tar.gz ./Ansible/*

      - name: Build
        run: |
          echo "Build Ansible artifact" > ansible_artifact.tar.gz
  
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'nightly'
          rm: true
          files: |
            ansible_artifact.tar.gz
