name: OpenMRS backend image build and push to Docker Hub

on:
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest

    environment: 
      name: dev
      url: |
        'https://lime-dev.ocg.msf.org'
        'https://hub.docker.com/repository/docker/msfocg/openmrs3-backend'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-backend:dev
          cache-from: type=gha 
          cache-to: type=gha,mode=max

  build-qa:
    runs-on: ubuntu-latest

    needs: [build-dev]

    if: github.ref == 'refs/heads/qa' || github.ref == 'refs/remotes/origin/qa' 

    environment: 
      name: qa
      url: 'https://lime-qa.ocg.msf.org/'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-backend:qa
          cache-from: type=gha 
          cache-to: type=gha,mode=max

  build-prod:
    runs-on: ubuntu-latest

    needs: [build-qa]
    
    if: github.ref == 'refs/heads/prod' || github.ref == 'refs/remotes/origin/prod' 

    environment: 
      name: prod
      url: 'https://lime.ocg.msf.org/'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-backend:latest
          cache-from: type=gha 
          cache-to: type=gha,mode=max
