name: OpenMRS backend image build and push to Docker Hub

on:
  push:
    tags:
      - "*"
    paths:
      - "Dockerfile"
      - "pom.xml"
      - "/distro/distro.properties"
      - "/distro/pom.xml"
      - ".github/workflows/build-backend.yml"
    branches:
      - "*"

  pull_request:
    branches:
      - "*"
    paths:
      - "Dockerfile"
      - "pom.xml"
      - "/distro/distro.properties"
      - "/distro/pom.xml"
      - ".github/workflows/build-backend.yml"
    types: [opened, synchronize]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  BuildDev:
    runs-on: ubuntu-latest

    if: endsWith(github.ref, 'dev')

    environment: 
      name: dev
      url: 'https://lime-dev.ocg.msf.org/'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-backend:dev
          cache-from: type=gha 
          cache-to: type=gha,mode=max

  BuildStaging:
    runs-on: ubuntu-latest

    needs: BuildDev

    if: ${{ github.event_name == 'pull_request' && endsWith(github.ref, 'qa')  }}

    environment: 
      name: qa
      url: 'https://lime-qa.ocg.msf.org/'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-backend:qa
          cache-from: type=gha 
          cache-to: type=gha,mode=max

          