name: OpenMRS frontend image build and push to Docker Hub

on:
  push:
    tags:
      - "*"
    paths:
      - "/frontend/Dockerfile"
      - "/frontend/spa-build-config.json"
      - ".github/workflows/build-frontend.yml"
    branches:
      - "*"

  pull_request:
    branches:
      - "*"
    paths:
      - "/frontend/Dockerfile"
      - "/frontend/spa-build-config.json"
      - ".github/workflows/build-frontend.yml"
    types: [opened, synchronize]
  release:
    types:
      - created

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:frontend"
          file: /frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-frontend:dev