name: OpenMRS backend image build and push to Docker Hub

on:
  push:
    tags:
      - "*"
    paths:
      - "Dockerfile"
      - "pom.xml"
      - "/distro/distro.properties"
      - "/distro/pom.xml"
      - ".github/workflows/build-backend.yml"
    branches:
      - "*"

  pull_request:
    branches:
      - "*"
    paths:
      - "Dockerfile"
      - "pom.xml"
      - "/distro/distro.properties"
      - "/distro/pom.xml"
      - ".github/workflows/build-backend.yml"
    types: [opened, synchronize]
  release:
    types:
      - created

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-backend:dev
          cache-from: type=gha 
          cache-to: type=gha,mode=max

  staging:
    runs-on: ubuntu-latest

    needs: dev

    if: ${{ github.ref == 'refs/heads/qa' }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-backend:qa
          cache-from: type=gha 
          cache-to: type=gha,mode=max

          