name: Clear cache

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    name: Delete all caches
    runs-on: ubuntu-20.04

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@v2
        with:
          github-token:
            description: 'Your GITHUB_TOKEN.'
            required: false
            default: ${{ secrets._GITHUB_TOKEN }}
          dry-run: 'false'
