name: Clear all Github actions caches on sundays
on:
  workflow_dispatch:

jobs:
  clear-cache:
    name: Delete all caches
    runs-on: ubuntu-latest

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          github-token:
            required: false
            default: ${{ secrets._GITHUB_TOKEN }}
          dry-run: 'true'
