name: Upload Configuration Artifact

on:
  push:
    tags:
      - "*"
    paths:
      - "/distro/configuration/**"
    branches:
      - "*"

  pull_request:
    branches:
      - "*"
    types: [opened, synchronize]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tar files
        run: tar -cvf configuration_artifact.tar ./distro/configuration

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: configuration-artifact
          path: configuration_artifact.tar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: /config/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-config:dev
          cache-from: type=gha 
          cache-to: type=gha,mode=max
