name: Update documentation

on:
  push:
    paths:
    - 'docs/**'
  pull_request:
    paths: 
    - 'docs/**'

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: tool3/docsify-action@v1.0.3
      with:
        github_token: ${{ secrets._GITHUB_TOKEN }}