name: Update documentation on GitHub Pages

on:
  push:
    paths:
    - 'docs/**'
    - ".github/workflows/docs.yml"
  pull_request:
    paths: 
    - 'docs/**'
    - ".github/workflows/docs.yml"

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docsify site
        uses: tool3/docsify-action@v1.1.0
        with:
          args: docs
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs