name: Update documentation on GitHub Pages

on:
  push:
    paths:
    - 'docs/**'
    - ".github/workflows/docs.yml"
  pull_request:
    paths: 
    - 'docs/**'
    - ".github/workflows/docs.yml"

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install -g docsify-cli
          npm install
      - name: Build
        run: |
          docsify build docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/