name: Update documentation on GitHub Pages

on:
  push:
    paths:
    - 'docs/**'
    - ".github/workflows/docs.yml"
  pull_request:
    paths: 
    - 'docs/**'
    - ".github/workflows/docs.yml"

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets._GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./docs