name: Package Installation Files

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'setup/**'
  pull_request:
    paths:
      - 'setup/**'

jobs:
  upload-artifact:
      name: '📦 Release'
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Zip the installation folder
        run: zip -r installation.zip ./Ansible/*

      - name: Gzip the installation folder
        run: gzip -r installation.gzip ./Ansible
  
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'nightly'
          rm: true
          files: |
            installation.zip
            installation.gzip
